// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmg3WKRL-e6daKLMuQhNNcYWatlAxrVOA',
    appId: '1:194359617378:web:d11ec746dd592682ab2e3b',
    messagingSenderId: '194359617378',
    projectId: 'tekrare-5eac1',
    authDomain: 'tekrare-5eac1.firebaseapp.com',
    storageBucket: 'tekrare-5eac1.firebasestorage.app',
    measurementId: 'G-MMVZPBP5XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0db5C36pBXTUBNQAJTvJMDhfzDuvJDU',
    appId: '1:194359617378:android:e7ca15fae23c4681ab2e3b',
    messagingSenderId: '194359617378',
    projectId: 'tekrare-5eac1',
    storageBucket: 'tekrare-5eac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpTwWPt1oVrVz8z_wbJnm70Uh30LZREEs',
    appId: '1:194359617378:ios:ed3cf4aeea162427ab2e3b',
    messagingSenderId: '194359617378',
    projectId: 'tekrare-5eac1',
    storageBucket: 'tekrare-5eac1.firebasestorage.app',
    androidClientId: '194359617378-o0eq3qn32tjq8n6ep22sb3v2o6h4a029.apps.googleusercontent.com',
    iosClientId: '194359617378-21cjl0akohkrfhvcl59ngso6i3p8acg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpTwWPt1oVrVz8z_wbJnm70Uh30LZREEs',
    appId: '1:194359617378:ios:ed3cf4aeea162427ab2e3b',
    messagingSenderId: '194359617378',
    projectId: 'tekrare-5eac1',
    storageBucket: 'tekrare-5eac1.firebasestorage.app',
    androidClientId: '194359617378-o0eq3qn32tjq8n6ep22sb3v2o6h4a029.apps.googleusercontent.com',
    iosClientId: '194359617378-21cjl0akohkrfhvcl59ngso6i3p8acg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmg3WKRL-e6daKLMuQhNNcYWatlAxrVOA',
    appId: '1:194359617378:web:a4203a825b1dd55dab2e3b',
    messagingSenderId: '194359617378',
    projectId: 'tekrare-5eac1',
    authDomain: 'tekrare-5eac1.firebaseapp.com',
    storageBucket: 'tekrare-5eac1.firebasestorage.app',
    measurementId: 'G-EN8DKTRZBV',
  );

}